webtalk_init -webtalk_dir C:/Users/jsickafo/Downloads/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/lab2_tests_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 17 12:42:36 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5dbebc23-d483-450c-ac98-f59495a87c49" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "812cdeb609d44ef3b1500e0ccf7d667c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM)2 Duo CPU     E8500  @ 3.16GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3159 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5768_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2247507770 -regid "" -xml C:/Users/jsickafo/Downloads/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/lab2_tests_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/jsickafo/Downloads/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/lab2_tests_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/jsickafo/Downloads/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/lab2_tests_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
